# Generated by Django 2.2 on 2019-11-21 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('number_of_page', models.IntegerField(blank=True, null=True)),
                ('type_of_book', models.CharField(blank=True, choices=[('one of novel', 'One of Novel'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=100)),
            ],
        ),
    ]
